/* Document intake (ADR-0022): a CV arrives once as a PDF or Word file and
   is structured once. The fixtures are fictional and regenerated by
   tests/fixtures/make-fixtures.mjs. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { extractDocument, sniffFormat, docxText, decodeUpload, DocumentError, MAX_DOCUMENT_BYTES } from '../src/spine/documents.ts';
import { structureResume, parseResumeLoose } from '../src/spine/agents.ts';

const fixture = (name: string) => new Uint8Array(readFileSync(new URL(`./fixtures/${name}`, import.meta.url)));

test('format comes from the bytes, not the name', () => {
  assert.equal(sniffFormat(fixture('cv-two-column.pdf')), 'pdf');
  assert.equal(sniffFormat(fixture('cv-word.docx')), 'docx');
  assert.equal(sniffFormat(new TextEncoder().encode('plain text pretending to be a pdf')), null);
});

test('a two-column PDF is read column by column, not interleaved', async () => {
  const doc = await extractDocument(fixture('cv-two-column.pdf'));
  assert.equal(doc.parser, 'liteparse');
  const r = structureResume(doc.text);
  assert.deepEqual(r.roles.map(x => [x.title, x.company, x.start, x.end]), [
    ['Senior Backend Engineer', 'Harbourline', '03/2020', 'Present'],
    ['Backend Engineer', 'Copperleaf', '09/2016', '02/2020'],
  ]);
  assert.equal(r.roles[0]!.bullets.length, 2);
  assert.ok(!r.roles.some(x => x.bullets.some(b => /Bristol|Skills|Kafka, cutting/.test(b) && /Bristol|Skills/.test(b))),
    'no sidebar text leaks into experience bullets');
  assert.equal(r.email, 'ravi.menon@example.com');
  assert.equal(r.location, 'Bristol, UK');
});

test('a Word file is read without LibreOffice: deflate, tabs and list bullets', async () => {
  const doc = await extractDocument(fixture('cv-word.docx'));
  assert.equal(doc.parser, 'docx-xml');
  assert.match(doc.text, /^- Cut late deliveries/m, 'numbered paragraphs become bullets');
  const r = structureResume(doc.text);
  assert.deepEqual(r.roles.map(x => [x.title, x.company, x.start, x.end]), [
    ['Operations Manager', 'Kestrel Logistics', '04/2019', 'Present'],
    ['Shift Supervisor', 'Pennine Freight', '2015', '2019'],
  ]);
  assert.ok(r.roles[0]!.bullets[1]!.includes('& ran weekly'), 'XML entities decoded');
});

test('the tolerant reader handles common real-world shapes', () => {
  const r = parseResumeLoose([
    'Jordan Lee', 'Product Designer', 'Manchester, UK | jordan@example.com | +44 7700 900123', '',
    'Work Experience',
    'Senior Product Designer at Brightpay', 'Jan 2021 – Present',
    '• Redesigned onboarding, lifting activation from 31% to 44%.',
    '• Led a design system adopted by 6 squads and maintained', 'across web and mobile.',
    'Data Engineer', 'Northwind Analytics, London    2019 to 2022', '- Built Spark pipelines.',
    'Skills', 'Figma, Prototyping | Accessibility',
  ].join('\n'));
  assert.deepEqual(r.roles.map(x => [x.title, x.company, x.start, x.end]), [
    ['Senior Product Designer', 'Brightpay', '01/2021', 'Present'],
    ['Data Engineer', 'Northwind Analytics, London', '2019', '2022'],
  ]);
  assert.match(r.roles[0]!.bullets[1]!, /maintained across web and mobile\.$/, 'wrapped bullet rejoined');
  assert.equal(r.location, 'Manchester, UK');
  assert.deepEqual(r.skills[0]!.items, ['Figma', 'Prototyping', 'Accessibility']);
});

test('the seeded template still takes the strict path', () => {
  const r = structureResume('Nadia Rowe\nEngineer\nLondon | 1 | n@example.com\nEXPERIENCE\nAcme | Engineer | 01/2020 - 02/2021\n- Did a thing');
  assert.equal(r.structuredBy, 'template');
  assert.equal(r.roles[0]!.company, 'Acme');
});

test('refusals are specific: empty, too large, wrong format, no text layer', async () => {
  const code = async (bytes: Uint8Array) => {
    try { await extractDocument(bytes); return 'ok'; } catch (e) { return (e as DocumentError).code; }
  };
  assert.equal(await code(new Uint8Array(0)), 'empty_document');
  assert.equal(await code(new Uint8Array(MAX_DOCUMENT_BYTES + 1)), 'document_too_large');
  assert.equal(await code(new TextEncoder().encode('hello')), 'unsupported_format');
  assert.throws(() => decodeUpload(''), DocumentError);
  assert.equal(decodeUpload('data:application/pdf;base64,JVBERi0=').length, 5);
  /* A Word file with almost no text (an empty template) is refused, not
     structured into nothing. */
  const { deflateRawSync } = await import('node:zlib');
  const xml = Buffer.from('<w:document><w:body><w:p><w:r><w:t>Hi</w:t></w:r></w:p></w:body></w:document>');
  const comp = deflateRawSync(xml);
  const name = Buffer.from('word/document.xml');
  const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(8, 8);
  local.writeUInt32LE(comp.length, 18); local.writeUInt32LE(xml.length, 22); local.writeUInt16LE(name.length, 26);
  const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50, 0); central.writeUInt16LE(8, 10);
  central.writeUInt32LE(comp.length, 20); central.writeUInt32LE(xml.length, 24); central.writeUInt16LE(name.length, 28);
  const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(1, 8); end.writeUInt16LE(1, 10);
  end.writeUInt32LE(46 + name.length, 12); end.writeUInt32LE(30 + name.length + comp.length, 16);
  const tinyDocx = new Uint8Array(Buffer.concat([local, name, comp, central, name, end]));
  assert.equal(docxText(tinyDocx), 'Hi');
  assert.equal(await code(tinyDocx), 'no_text_found');
});
